# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from resource import main_window_rc
class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(544, 423)
        mainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/ai.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setDocumentMode(False)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(0, 0, 544, 380))
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.widget.setMouseTracking(True)
        self.widget.setAcceptDrops(True)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-image: url(:/images/bg.png);")
        self.widget.setObjectName("widget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 380, 547, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 544, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menuDakai = QtWidgets.QMenu(self.menubar)
        self.menuDakai.setObjectName("menuDakai")
        mainWindow.setMenuBar(self.menubar)
        self.actionResNet50 = QtWidgets.QAction(mainWindow)
        self.actionResNet50.setCheckable(True)
        self.actionResNet50.setChecked(True)
        self.actionResNet50.setIconVisibleInMenu(True)
        self.actionResNet50.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionResNet50.setObjectName("actionResNet50")
        self.actionSqueezeNet = QtWidgets.QAction(mainWindow)
        self.actionSqueezeNet.setCheckable(True)
        self.actionSqueezeNet.setObjectName("actionSqueezeNet")
        self.actionInceptionV3 = QtWidgets.QAction(mainWindow)
        self.actionInceptionV3.setCheckable(True)
        self.actionInceptionV3.setObjectName("actionInceptionV3")
        self.actionDenseNet121 = QtWidgets.QAction(mainWindow)
        self.actionDenseNet121.setCheckable(True)
        self.actionDenseNet121.setObjectName("actionDenseNet121")
        self.version = QtWidgets.QAction(mainWindow)
        self.version.setObjectName("version")
        self.about_author = QtWidgets.QAction(mainWindow)
        self.about_author.setObjectName("about_author")
        self.open_image = QtWidgets.QAction(mainWindow)
        self.open_image.setObjectName("open_image")
        self.menu.addAction(self.actionDenseNet121)
        self.menu.addSeparator()
        self.menu.addAction(self.actionInceptionV3)
        self.menu.addSeparator()
        self.menu.addAction(self.actionResNet50)
        self.menu.addSeparator()
        self.menu.addAction(self.actionSqueezeNet)
        self.menu.addSeparator()
        self.menu_3.addAction(self.version)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.about_author)
        self.menuDakai.addAction(self.open_image)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuDakai.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "物体识别 by: Sohnia Zhu"))
        self.menu.setTitle(_translate("mainWindow", "识别模型"))
        self.menu_3.setTitle(_translate("mainWindow", "关于"))
        self.menuDakai.setTitle(_translate("mainWindow", "文件"))
        self.actionResNet50.setText(_translate("mainWindow", "ResNet50 （预测速度快 正确率较高）"))
        self.actionResNet50.setShortcut(_translate("mainWindow", "Ctrl+R"))
        self.actionSqueezeNet.setText(_translate("mainWindow", "SqueezeNet（预测速度最快 正确率中等）"))
        self.actionSqueezeNet.setShortcut(_translate("mainWindow", "Ctrl+S"))
        self.actionInceptionV3.setText(_translate("mainWindow", "InceptionV3（预测速度慢 正确率高）"))
        self.actionInceptionV3.setShortcut(_translate("mainWindow", "Ctrl+I"))
        self.actionDenseNet121.setText(_translate("mainWindow", "DenseNet121（预测速度更慢 正确率最高）."))
        self.actionDenseNet121.setShortcut(_translate("mainWindow", "Ctrl+D"))
        self.version.setText(_translate("mainWindow", "版本信息"))
        self.version.setShortcut(_translate("mainWindow", "Ctrl+Alt+V"))
        self.about_author.setText(_translate("mainWindow", "关于作者"))
        self.about_author.setShortcut(_translate("mainWindow", "Ctrl+Alt+A"))
        self.open_image.setText(_translate("mainWindow", "打开文件"))
        self.open_image.setToolTip(_translate("mainWindow", "打开文件"))
        self.open_image.setShortcut(_translate("mainWindow", "Ctrl+O"))


